### ISSUE TITLE
The Template setContent method does not work well

### ISSUE THREAD

**Issue by lCHECHOl** [addgod/laravel-mandrill-template#1]
I am submitting a template as follows. To fill the variables of my template, I send the setContent method with an array of the variable I need and its value, but at the time the template_content key is sent it is equal to null, I don't know why, the same thing happens with the addContent method.

```php
$template = new Template('pruebas-2');
$template->setContent(['CURRENT_YEAR' => \Carbon\Carbon::now()->format('Y-m-d H:i')]);
$message = new Message();
$message->setSubject('Subject personalizado')->setFromEmail(config('mail.from.address'))->setFromName(config('mail.from.name'))->setMergeVars([]);
$message->addRecipient(new Recipient('sergio.benavides@licitaciones.info', 'Sergio Benavides', Type::TO));
MandrillTemplateFacade::send($template, $message);
```
and I am getting this:

```json
{
    "template_name": "pruebas-2",
    "template_content": null,
    "message": {
        "subject": "Subject personalizado",
        "from_email": "servicioalcliente@licitaciones.info",
        "from_name": "Licitaciones.info",
        "to": [
            {
                "email": "sergio.benavides@licitaciones.info",
                "name": "Sergio Benavides",
                "type": "to"
            }
        ],
        "headers": [],
        "preserve_recipients": false,
        "merge": true,
        "merge_language": "handlebars",
        "global_merge_vars": [],
        "merge_vars": [],
        "tags": [],
        "metadata": [],
        "recipient_metadata": [],
        "attachments": [],
        "images": []
    },
    "async": false,
    "ip_pool": null,
    "send_at": null,
    "key": "my_key"
}

Completed in 2,024.13ms
Got response: [{"email":"sergio.benavides@licitaciones.info","status":"sent","_id":"e0b31fe89d9e47a498856f6a8668b5d5","reject_reason":null}]
```

**Comment by lCHECHOl** [comment]
This solution worked for me https://github.com/addgod/laravel-mandrill-template/pull/2/commits/9d01cc87bce8f7fd29f7a83a22c46fea43d3451c, since in the send function of MandrillTemplate the second parameter is always null, and the sendTemplate function of the Mandrill_Messages class of mandril/mandril its second parameter is the content of the template

**Comment by ghost** [comment]
@lCHECHOl how do you get that response? thanks!!

**Comment by lCHECHOl** [comment]
> @lCHECHOl how do you get that response? thanks!!

I got it from my administration panel of the mandrill page, after doing the test from my code, you could be clearer about how I can help you, this problem I already solved it, it is to see if I can help you in any way, I am attentive.
