### ISSUE TITLE
setMergeVars not working

### ISSUE THREAD

**Issue by flagshippro** [addgod/laravel-mandrill-template#3]
I am sending array in setMergeVars but mandrill is not replacing the data

**Comment by pendolf** [comment]
@flagshippro Problem can be in "merge_language" param, this package use hardcoded value, but it can also be  "mailchimp". https://github.com/addgod/laravel-mandrill-template/blob/b7d6ec86590006bdc57af9156ebc629fd6464f90/src/Mandrill/Message.php#L592

**Comment by Betoxx1** [comment]
Im having same issue, I already checked the merge_language field in the vendor file and is shows the correct value:
`'merge_language'      => 'handlebars',`

**Comment by addgod** [comment]
This is now a config option.
