### ISSUE TITLE
Compatibility with Composer 2

### ISSUE THREAD

**Issue by isratmir** [addgod/laravel-mandrill-template#4]
Hi. Any plans on fixing compatibility with composer 2.0?

![image](https://user-images.githubusercontent.com/1897701/100995811-7cc15e00-3582-11eb-931a-fbae578f311d.png)

**Comment by addgod** [comment]
Yes this will be updated to composer 2, and to latest laravel version soon aswell.

**Comment by addgod** [comment]
This should be fixed.
